"""Database creation

Revision ID: 115cf67537d7
Revises: 
Create Date: 2023-02-22 12:31:20.041074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '115cf67537d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('user_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('login', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('hashed_password', mysql.TEXT(), nullable=False),
                    sa.Column('photo', mysql.VARCHAR(length=20), nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
                    sa.Column('s_name', mysql.VARCHAR(length=40), nullable=False),
                    sa.Column('b_day', sa.DATE(), nullable=False),
                    sa.Column('gender', mysql.ENUM('М', 'Ж'), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=250), nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
                    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
                    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
                    sa.PrimaryKeyConstraint('user_ID'),
                    sa.UniqueConstraint('login', 'email')
                    )
    op.create_table('Recipe',
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
                    sa.Column('photo', mysql.VARCHAR(length=50), nullable=False),
                    sa.Column('servings_cout', mysql.TINYINT(unsigned=True), nullable=False),
                    sa.Column('cook_time', mysql.TIME(), nullable=False),
                    sa.Column('rating', mysql.INTEGER(), nullable=False),
                    sa.Column('recommend', mysql.TEXT(), nullable=True),
                    sa.Column('author', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.CheckConstraint('servings_cout>0'),
                    sa.ForeignKeyConstraint(['author'], ['User.user_ID'], ),
                    sa.PrimaryKeyConstraint('recipe_ID'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('photo')
                    )
    op.create_table('Favourite_recipe',
                    sa.Column('favourite_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('user_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ),
                    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
                    sa.PrimaryKeyConstraint('favourite_ID')
                    )
    op.create_table('Recipe_ingredient',
                    sa.Column('recipe_ID_ingredient', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('ingredient_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('count', mysql.DECIMAL(unsigned=True, precision=5, scale=2), nullable=False),
                    sa.Column('unit_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.CheckConstraint('count>0'),
                    sa.ForeignKeyConstraint(['ingredient_ID'], ['Ingredient.ingredient_ID'], ),
                    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ),
                    sa.ForeignKeyConstraint(['unit_ID'], ['Unit.unit_ID'], ),
                    sa.PrimaryKeyConstraint('recipe_ID_ingredient')
                    )
    op.create_table('Recipe_tag',
                    sa.Column('recipe_ID_tag', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('tag_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ),
                    sa.ForeignKeyConstraint(['tag_ID'], ['Tag.tag_ID'], ),
                    sa.PrimaryKeyConstraint('recipe_ID_tag')
                    )
    op.create_table('Score_recipe',
                    sa.Column('Score_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('user_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('score', mysql.TINYINT(), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ),
                    sa.ForeignKeyConstraint(['user_ID'], ['User.user_ID'], ),
                    sa.PrimaryKeyConstraint('Score_ID')
                    )
    op.create_table('Step',
                    sa.Column('step_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.Column('description', mysql.TEXT(), nullable=False),
                    sa.Column('timer', mysql.TIME(), nullable=True),
                    sa.Column('media', mysql.VARCHAR(length=20), nullable=True),
                    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ),
                    sa.PrimaryKeyConstraint('step_ID'),
                    sa.UniqueConstraint('media')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Step')
    op.drop_table('Score_recipe')
    op.drop_table('Recipe_tag')
    op.drop_table('Recipe_ingredient')
    op.drop_table('Favourite_recipe')
    op.drop_table('Recipe')
    op.drop_table('User')
    # ### end Alembic commands ###
