"""Db

Revision ID: bddc2ce184ca
Revises: 
Create Date: 2023-03-25 21:08:49.543055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bddc2ce184ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('tag_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('tag_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Unit',
    sa.Column('unit_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('unit_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('login', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('hashed_password', mysql.TEXT(), nullable=False),
    sa.Column('photo', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('photo_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('s_name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('b_day', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.ENUM('М', 'Ж'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('Ingredient',
    sa.Column('ingredient_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('unit_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('kkal', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('belki', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('zhiry', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('uglevody', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['unit_ID'], ['Unit.unit_ID'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ingredient_ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Recipe',
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('photo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('photo_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('servings_cout', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('cook_time', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('rating', mysql.INTEGER(), nullable=False),
    sa.Column('recommend', mysql.TEXT(), nullable=True),
    sa.Column('author', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('Kkal', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('Belky', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('Zhyri', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('Uglevody', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.CheckConstraint('servings_cout>0'),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('recipe_ID'),
    sa.UniqueConstraint('photo')
    )
    op.create_table('Favourite_recipe',
    sa.Column('favourite_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favourite_ID')
    )
    op.create_table('Recipe_ingredient',
    sa.Column('recipe_ID_ingredient', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('ingredient_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('count', mysql.DECIMAL(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('count>=0'),
    sa.ForeignKeyConstraint(['ingredient_ID'], ['Ingredient.ingredient_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_ID_ingredient'),
    sa.UniqueConstraint('recipe_ID', 'ingredient_ID')
    )
    op.create_table('Recipe_tag',
    sa.Column('recipe_ID_tag', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('tag_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_ID'], ['Tag.tag_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_ID_tag')
    )
    op.create_table('Score_recipe',
    sa.Column('Score_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('score', mysql.TINYINT(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ID'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Score_ID'),
    sa.UniqueConstraint('recipe_ID', 'user_ID')
    )
    op.create_table('Step',
    sa.Column('step_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('timer', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('media', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('media_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('recipe_ID', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_ID'], ['Recipe.recipe_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_ID'),
    sa.UniqueConstraint('media')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Step')
    op.drop_table('Score_recipe')
    op.drop_table('Recipe_tag')
    op.drop_table('Recipe_ingredient')
    op.drop_table('Favourite_recipe')
    op.drop_table('Recipe')
    op.drop_table('Ingredient')
    op.drop_table('user')
    op.drop_table('Unit')
    op.drop_table('Tag')
    # ### end Alembic commands ###
